#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

local custom_files=(
  "aliases.zsh"
  "env.zsh"
  "functions.zsh"
  "secret.zsh"
)

for file in "${custom_files[@]}"; do
  if [[ -f "$ZDOTDIR/$file" ]]; then
    source "$ZDOTDIR/$file"
  fi
done

